Create a 3*3 array using list_1 = [1,2,3] list_2 = [4,5,6] list_3 = [7,8,9]


In [9]:
list_1 = [1,2,3] 
list_2 = [4,5,6] 
list_3 = [7,8,9]

import numpy as np
array_1 = np.row_stack([list_1,list_2,list_3])
print(array_1)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


We can create above simply by array method as well.

In [10]:
array_1 = np.array([list_1,list_2,list_3])
print(array_1)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


We can also add the above lists in the form of columns

In [7]:
array_1 = np.column_stack([list_1,list_2,list_3])
print(array_1)

[[1 4 7]
 [2 5 8]
 [3 6 9]]


Perform an element-wise multiplication using list_1 = [2,3,4,5] list_2 = [7,8,9,6] and obtain the output as a list. 
Hint: Convert the list to an array and after multiplication convert it back to a list.

In [12]:
list_1 = [2,3,4,5] 
list_2 = [7,8,9,6]
array_1 = np.array(list_1)
array_2 = np.array(list_2)
array_3 = array_1*array_2

print(list(array_3))

[14, 24, 36, 30]
