Create a 3*3 array using list_1 = [1,2,3] list_2 = [4,5,6] list_3 = [7,8,9]


In [3]:
list_1 = [1,2,3] 
list_2 = [4,5,6] 
list_3 = [7,8,9]

import numpy as np
array_1 = np.row_stack([list_1,list_2,list_3])
print(array_1)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


We can create above simply by array method as well.

In [10]:
array_1 = np.array([list_1,list_2,list_3])
print(array_1)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


We can also add the above lists in the form of columns

In [7]:
array_1 = np.column_stack([list_1,list_2,list_3])
print(array_1)

[[1 4 7]
 [2 5 8]
 [3 6 9]]


Perform an element-wise multiplication using list_1 = [2,3,4,5] list_2 = [7,8,9,6] and obtain the output as a list. 
Hint: Convert the list to an array and after multiplication convert it back to a list.

In [12]:
list_1 = [2,3,4,5] 
list_2 = [7,8,9,6]
array_1 = np.array(list_1)
array_2 = np.array(list_2)
array_3 = array_1*array_2

print(list(array_3))

[14, 24, 36, 30]


### <b> Ways to create Numpy

1. array() -  arguments - any sequence (tuple,list), dtype =  It is useful when we want to upcast

2. arange() - It is same like range function, but to create numpy array. 
              arguments - start , stop, step, dtype
              start (0 default), step (1 defalt) and dtype (default = int) are optional
              

3. zeroes() - shape and dtype - To create array containing zeroes
              dtype = float
              
4. ones() - shape and dtype - To create array containing zeroes
              dtype = float
              
5. empty()    shape and dtype - To create array containing zeroes
              dtype = float
              intialized the array with given shape and array but without data.
6. linspace() - It is same like arange. but some differences
                 start, stop -  mandatory
                 num defaut = 50
                 dtype = by default infer based on data
                 retstep = Returns step, if value is true
                 endpoint = Exclde upper bound ,if value is true.
                 
7. eye() -  it creates array of m*n  - m=n if not specified (n is optional)
            k = ny default 0. It takes middle diagnal.
            dtype = float
          
8. identity() - same as eye method. It creates square matrix and has only 2 parameters.
                m = size, dtype = float by default
                
9. random.rand() - It creates random values based on parameters

In [4]:
np.array((1,2,3),dtype='complex')

array([1.+0.j, 2.+0.j, 3.+0.j])

In [5]:
np.arange(100)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [6]:
np.arange(10,101,10,dtype='float')

array([ 10.,  20.,  30.,  40.,  50.,  60.,  70.,  80.,  90., 100.])

In [10]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

It means 2 rows and 3 columns

In [12]:
np.zeros(5,dtype='int')

array([0, 0, 0, 0, 0])

In [13]:
np.ones(5,dtype='int')

array([1, 1, 1, 1, 1])

In [14]:
np.empty(5,dtype='int')

array([           43210528,                   0, 5188277033812703315,
           140459656327920,                  48])

In [24]:
np.linspace(5,100,num=10,retstep=True,endpoint=False)

(array([ 5. , 14.5, 24. , 33.5, 43. , 52.5, 62. , 71.5, 81. , 90.5]), 9.5)

In [25]:
np.linspace(1,100)

array([  1.        ,   3.02040816,   5.04081633,   7.06122449,
         9.08163265,  11.10204082,  13.12244898,  15.14285714,
        17.16326531,  19.18367347,  21.20408163,  23.2244898 ,
        25.24489796,  27.26530612,  29.28571429,  31.30612245,
        33.32653061,  35.34693878,  37.36734694,  39.3877551 ,
        41.40816327,  43.42857143,  45.44897959,  47.46938776,
        49.48979592,  51.51020408,  53.53061224,  55.55102041,
        57.57142857,  59.59183673,  61.6122449 ,  63.63265306,
        65.65306122,  67.67346939,  69.69387755,  71.71428571,
        73.73469388,  75.75510204,  77.7755102 ,  79.79591837,
        81.81632653,  83.83673469,  85.85714286,  87.87755102,
        89.89795918,  91.91836735,  93.93877551,  95.95918367,
        97.97959184, 100.        ])

In [26]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [28]:
np.eye(5,4,k=1,dtype='int')

array([[0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [34]:
np.identity(5,dtype=int)

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

In [38]:
np.random.rand(5,5)

array([[0.78761596, 0.76648004, 0.79371629, 0.87069655, 0.68310335],
       [0.3811785 , 0.91304612, 0.64834748, 0.06848252, 0.75061001],
       [0.73218209, 0.22206407, 0.46108264, 0.89472019, 0.62351808],
       [0.02271169, 0.25264093, 0.97449795, 0.60594306, 0.69565984],
       [0.16467611, 0.17092547, 0.79846159, 0.19127157, 0.98021382]])

### Attributes of an Array

1. ndim = to get dimensions
2. shape - to get number of rows and columns
3. size = to get number of elements
4. dtype - to get data type
5. itemsize - to get size of each item

In [44]:
a = np.identity(5,dtype='int32')
print(a)
print("shape: "+str(a.shape))
print("dimension: "+ str(a.ndim))
print("size: "+str(a.size))
print("dtype: "+str(a.dtype))
print("itemsize: "+str(a.itemsize))

[[1 0 0 0 0]
 [0 1 0 0 0]
 [0 0 1 0 0]
 [0 0 0 1 0]
 [0 0 0 0 1]]
shape: (5, 5)
dimension: 2
size: 25
dtype: int32
itemsize: 4


astype() -  This method is used to chnage the datatype of an array.

In [46]:
a.astype(float)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

## Advanced Indexing

In [77]:
a=np.ones((4,4),dtype=int)
print(a)

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


In [79]:
a[1:-1,1:-1]=0
print(a)

[[1 1 1 1]
 [1 0 0 1]
 [1 0 0 1]
 [1 1 1 1]]


In [80]:
a[a>0]=7

In [81]:
print(a)

[[7 7 7 7]
 [7 0 0 7]
 [7 0 0 7]
 [7 7 7 7]]


## Broadcasting

In [82]:
print(a+2)

[[9 9 9 9]
 [9 2 2 9]
 [9 2 2 9]
 [9 9 9 9]]


Internally It creates the array of 2 of size (5,5) and then add.

There are 3 rules of broadcasting:
1. If dimension of both arrays are not same. Then we will add 1 from left side to make the dimensions equal.
2. Then we start from right side to left side and verify, whether size is same for each dimension. If size is not same the rule 3
3. Either of dimension should be 1.


In [84]:
a=np.array([1,2])
b=np.array([[5,5],[6,6]])
a+b

array([[6, 7],
       [7, 8]])

In above example 
a has size (2) and b has size (2,2). 
then 1 is added before 2. size of a becomes (1,2)
Now, we compare as per rule 2 and 3. It satisfies and hence we got output.

## Reshaping Arrays